### ISSUE TITLE
Gopher browser file seems missing

### ISSUE THREAD

**Issue by Gunny1980** [nihirash/internet-nextplorer#5]
Good evening,  Nihirash

After watching TJ Ferreira's splendid You Tube video I have come to download your Nextplorer files.  On the video, he loads a browser file.  I can't for the life of me find that particular file amongst your code.  Maybe I'm doing something dopey or missing the obvious?

Thanks and congratulations on your great work.

Dave

**Comment by nihirash** [comment]
Hello!

Latest published release located here(in releases page): https://github.com/nihirash/internet-nextplorer/releases/tag/0.3.0
